query findMakerById {
  findMakerById(id: 1196) {
    name
    id
  }
}

query findMakers {
  findMakers(order: [{ column: "name", direction: "desc" }]) {
    name
    id
  }
}

mutation addMaker {
  addMaker(name: "XXXXXX") {
    name
    id
  }
}

mutation updateMaker {
  updateMaker(
    id: 1196
    data:{
      name: "Zzzzzzz"
    }
    
	) {
    name
    id
  }
}

mutation deleteMaker {
  deleteMaker(id: 1196) {
    id
    name
  }
}
