query findProductCategoryById {
  findProductCategoryById(id: 4776) {
    name
    id
  }
}

query findProductCategories {
  findProductCategories {
    name
    id
  }
}

mutation addProductCategory {
  addProductCategory(name: "XXXXXX") {
    name
    id
  }
}

mutation updateProductCategory {
  updateProductCategory(id: 4775, data: { name: "vvvvvvvvvvvv" }) {
    name
    id
  }
}

mutation deleteProductCategory {
  deleteProductCategory(id: 4775) {
    id
  }
}
