mutation updateProduct {
  updateProduct(
    id: "612"
    data:{
      name: "ehey there"
      tags: []
      productCategories: []
      makers: []
      youtubeVideos: [1,3]
    }
  ) {
    name
    id
    tags {
      name
      tagCategory {
        name
      }
    }
    productCategories {
      name
    }
    youtubeVideos {
      description
    }
    makers {
      name
    }
  }
}

mutation deleteProduct {
  deleteProduct(id: 611) {
    id
  }
}

mutation addProduct {
  addProduct(
    name: "XXXXXX"
    tags: []
    productCategories: []
    makers: []
    youtubeVideos: [1]
  ) {
    name
    id
    tags {
      name
      id
      tagCategory {
        name
      }
    }
    productCategories {
      name
    }
    youtubeVideos {
      description
    }
  }
}

query findProductById {
  findProductById(id: "601") {
    name
    id
    productCategories {
      name
      id
    }
    makers {
      name
      id
    }
    tags {
      name
      id
      tagCategory {
        name
      }
    }
    youtubeVideos {
      description
    }
  }
}

query queryProducts {
  queryProducts(
    query: { productCategories: [4777], tags: [], makers: [1192] }
    order: [{ column: "name", direction: "desc" }]
  ) {
    name
    id
    productCategories {
      name
      id
    }
    makers {
      name
      id
    }
    tags {
      name
      id
      # tagCategory {
      #   name
      # }
    }
    youtubeVideos {
      description
    }
  }
}

query findProducts {
  findProducts(offset:1, limit:50) {
    name
    id
    price
    productCategories {
      name
      id
    }
    makers {
      name
      id
    }
    tags {
      name
      id
      tagCategory {
        name
      }
    }
    youtubeVideos {
      description
    }
  }
}