query findTagCategoryById {
  findTagCategoryById(id: 9) {
    name
    id
  }
}

query findTagCategories {
  findTagCategories {
    name
    id
  }
}

mutation addTagCategory {
  addTagCategory(name: "XXXXXX", tagCategory:1) {
    name
    id
  }
}

mutation updateTagCategory {
  updateTagCategory(id: 1, data:{name: "qqqqqqqq"}) {
    name
    id
  }
}

mutation deleteTagCategory {
  deleteTagCategory(id: 8) {
    id
    name
  }
}
