query findTagById {
  findTagById(id: 1) {
    name
    id
    tagCategory {
      name
      id
    }
  }
}

query findTags {
  findTags {
    name
    id
    tagCategory {
      name
      id
    }
  }
}

mutation addTag {
  addTag(name: "XXXXXX", tagCategory: 2) {
    name
    id
    tagCategory {
      name
    }
  }
}

mutation updateTag {
  updateTag(id: 4, data: { name: "f", tagCategory: 999 }) {
    name
    id
    tagCategory {
      name
    }
  }
}

mutation deleteTag {
  deleteTag(id: 4) {
    id
    name
    tagCategory {
      name
    }
  }
}
